; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CCameraView
LastTemplate=CView
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "camera.h"
LastPage=0

ClassCount=1

ResourceCount=0
Class1=CCameraView

[CLS:CCameraView]
Type=0
HeaderFile=CameraView.h
ImplementationFile=CameraView.cpp
BaseClass=CView
Filter=C
LastObject=CCameraView
VirtualFilter=VWC

