//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by camera.rc
//
#define IDM_SELECT_CAMERA_1             40001
#define IDM_SELECT_CAMERA_2             40002
#define IDM_FFT                         40003
#define IDM_FILTERING                   40004
#define IDM_PACKET_FINDER               40006
#define IDM_FOV_UPDATE                  40007
#define IDM_FOV_RECREATE                40008
#define IDM_FOV_SAVE                    40009
#define IDM_bottom_edge                 40010
#define IDM_top_edge                    40011
#define IDM_left_edge                   40012
#define IDM_right_edge                  40013
#define IDM_BASE_DETECTOR               40014
#define IDM_PACKET_FINDER2              40015
#define IDM_HALL_COORDINATES            40016
#define IDM_HALL_COORDINATES_2          40017
#define IDM_PACKET_FINDER3              40018
#define IDM_FIDUCIAL                    40019
#define IDM_FID_X_DEC                   40020
#define IDM_FID_X_INC                   40021
#define IDM_FID_Y_DEC                   40022
#define IDM_FID_Y_INC                   40023
#define IDM_INITIAL_FIDUCIAL_POINT      40024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
